version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_BASE}
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
      - PGADMIN_LISTEN_PORT=${PG_ADMIN_PORT}
    ports:
      - "${PG_ADMIN_PORT}:${PG_ADMIN_PORT}"
    depends_on:
      - db
    healthcheck:
      disable: true
  web:
    build: .
    restart: always
    command: npm run start:dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    # environment:
    #  - NODE_ENV=production
